# docker-compose.yml #
version: "3"
services:
  app:
    image: php:alpine
    volumes:
      - "./:/app"
    working_dir: /app
    command: "php artisan serve --host=0.0.0.0 --port=80"
    expose:
      - 80
    environment:
      VIRTUAL_HOST: livechats.mikolaj.dk
      LETSENCRYPT_HOST: livechats.mikolaj.dk
      LETSENCRYPT_EMAIL: mikoo1991@yahoo.com
  db:
    image: mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: livechats
    ports:
      - 3306:3306
    volumes:
      - "db-data:/var/lib/mysql/data"
volumes:
  db-data: {}
networks:
  default:
    external:
      name: nginx-proxy
