version: "3.4"
services:
  app:
    image: php:alpine
    volumes:
      - "./:/app"
    command: "php artisan serve --host=0.0.0.0 --port=80"
    expose:
      - 80
    environment:
      VIRTUAL_HOST: mychat.mikolaj.dk
      LETSENCRYPT_HOST: mychat.mikolaj.dk
      LETSENCRYPT_EMAIL: mikoo1991@yahoo.com
networks:
  default:
    external:
      name: nginx-proxy
