version: "3"

services:
  # App php-fpm service
  app:
    build: ./
    container_name: livechats_app
    restart: unless-stopped
    expose:
      - 80
    environment:
      VIRTUAL_HOST: chat.mikolaj.dk
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: chat.mikolaj.dk
      LETSENCRYPT_EMAIL: mikoo1991@yahoo.com
networks:
  default:
    external:
      name: nginx-proxy
