version: "3"

services:
  # App php-fpm service
  app:
    build: ./
    container_name: livechats_app
    restart: unless-stopped
    expose:
      - 80
    environment:
      VIRTUAL_HOST: livechats.mikolaj.dk
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: livechats.mikolaj.dk
      LETSENCRYPT_EMAIL: mikoo1991@yahoo.com
  db:
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: livechats
      MYSQL_USER: miko1991
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
volumes:
  dbdata:
    driver: local
networks:
  default:
    external:
      name: nginx-proxy
