version: "3.4"
services:
  app:
    image: php:alpine
    volumes:
      - "./:/app"
    working_dir: /app
    command: "php artisan serve --host=localhost --port=80"
    expose:
      - 80
    environment:
      VIRTUAL_HOST: livechats.mikolaj.dk
      LETSENCRYPT_HOST: livechats.mikolaj.dk
      LETSENCRYPT_EMAIL: mikoo1991@yahoo.com
networks:
  default:
    external:
      name: nginx-proxy
