version: '2'

services:
  app:
    container_name: laravel_app
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./storage:/var/www/storage
    env_file: '.env.prod'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"
  web:
    container_name: nginx_server
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./storage/logs/:/var/log/nginx
    expose:
      - 80
    environment:
      VIRTUAL_HOST: livechats.mikolaj.dk
  database:
    container_name: mysql_database
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=livechats"
      - "MYSQL_USER=testtest"
      - "MYSQL_PASSWORD=testtest"
      - "MYSQL_ROOT_PASSWORD=testtest"
    ports:
      - 8991:3306
volumes:
  dbdata:
