version: "3"

services:
  # App php-fpm service
  app:
    build: ./
    container_name: livechats_app
    restart: unless-stopped
    expose:
      - 80
    environment:
      VIRTUAL_HOST: chat.mikolaj.dk
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: chat.mikolaj.dk
      LETSENCRYPT_EMAIL: mikoo1991@yahoo.com
  db:
    container_name: livechats_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Spillet2018
      - MYSQL_DATABASE=livechats
      - MYSQL_USER=miko1991
      - MYSQL_PASSWORD=Spillet2018
    volumes:
      - dbdata:/var/lib/mysql/
volumes:
  dbdata:
    driver: local
networks:
  default:
    external:
      name: nginx-proxy
